# Generated by Django 5.1.2 on 2024-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('crew_member', 'Crew Member'), ('manager', 'Manager'), ('admin', 'Admin')], default='crew_member', max_length=20),
        ),
    ]
